# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9fa40aba6dc1be81ab886f03edc332738ef5f83a27e5a4051585b79c1f716dd75be67dcd28091c67b1a0e8d143a7996d98b30992eae31b8102ee19b4b749b4f
  instagram_client_id: b2a6299bdd2f46c4bcc75cfc66eed87e
  instagram_client_secret: 68f0dde9b6644ee59c9b2ee14bf53a52
  dropbox_client_id: z7h09ojdq3t1lfi
  dropbox_client_secret: 5de78piod8bpyln

test:
  secret_key_base: c3fb50c32aeab6b367875409fefe9d8af19122e0582a3085e1645279232b9b1f34efa4665d1a487697fd431dfe77e9dedfa364a653b0459042d14ff992198aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  instagram_client_id: <%= ENV['INSTAGRAM_CLIENT_ID'] %>
  instagram_client_secret: <%= ENV['INSTAGRAM_CLIENT_SECRET'] %>
  dropbox_client_id: <%= ENV['DROPBOX_CLIENT_ID'] %>
  dropbox_client_secret: <%= ENV['DROPBOX_CLIENT_SECRET'] %>
